import type { Metadata } from "next";
import { Julius_Sans_One } from "next/font/google";
import "./globals.css";

const julius = Julius_Sans_One({
  weight: "400",       // Julius Sans One only has 400
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${julius.className} ${julius.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
